name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        sudo apt-get install g++-multilib libc6-dev-i386
        make -f Makefile.linux
        make -f Makefile.linux vmdk
        make -f Makefile.linux cdrom
        make -f Makefile.linux floppy
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
          name: sanos
          path: linux/img
    
